version: '2'

services:
  svc-rand:
    image: svc-rand:latest
    links:
      - mongodb
      - redis
    ports:
      - "2005:2005"
    environment:
      - NODE_ENV=staging
      - DEBUG=rand:*
      - FOMO_ADDRESS=
      - FOMO_OWNER=
      - FOMO_ACTIVE_ADDRESS=
      - FOMO_ACTIVE_PRIVATE_KEY=
      - REDIS_IP=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_PWD=bettown2ol8
      - DB_HOST=127.0.0.1
      - DB_PORT=27017
      - DB_USER=root
      - DB_PWD=bettown2ol8
      - DB_NAME=rand-staging
      - WHITE_LIST=172.22.0.1,127.0.0.1,172.23.0.1,39.106.132.95
